spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/apollo_assurance
    username: postgres
    password: post2001
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true